### ISSUE TITLE
Readme.md 

### ISSUE THREAD

**Issue by gemrey13** [RyannKim327/DjangoPractice#1]
Pre mag gawa muna ng virtual environment bago i install ang django. Creating a virtual environment before installing Django is a recommended practice in Python development.

Nag i-isolated ng environment for your project, para ma-manage and install project-specific dependencies without interfering with other Python projects on your system

**Comment by RyannKim327** [comment]
> Pre mag gawa muna ng virtual environment bago i install ang django. Creating a virtual environment before installing Django is a recommended practice in Python development.
> 
> Nag i-isolated ng environment for your project, para ma-manage and install project-specific dependencies without interfering with other Python projects on your system

It was being mentioned under the Start Django Project already
